from __future__ import annotations

from .models import Asset, Evidence, PatentExclusivity, Trial, now_iso

ACCESS_DATE = "2026-07-01"


def ev(asset_id: str, idx: int, typ: str, title: str, summary: str, url: str, confidence: float = 0.55) -> Evidence:
    return Evidence(
        id=f"{asset_id}-ev-{idx}",
        asset_id=asset_id,
        evidence_type=typ,
        title=title,
        summary=summary,
        url=url,
        source_name="Synthetic MVP seed source" if "example.com" in url else title.split(":")[0],
        date=ACCESS_DATE,
        extracted_facts={
            "citation_format": {
                "source_title": title,
                "source_url": url,
                "date_accessed": ACCESS_DATE,
                "source_type": typ,
                "quote_or_paraphrase": summary,
                "confidence": confidence,
            },
            "needs_verification": "example.com" in url,
        },
        confidence=confidence,
    )


def trial(asset_id: str, nct_id: str, phase: str, status: str, sponsor: str, indication: str, months_stale: int) -> Trial:
    return Trial(
        asset_id=asset_id,
        nct_id=nct_id,
        phase=phase,
        status=status,
        sponsor=sponsor,
        collaborators=[],
        enrollment=48 if "1/2" in phase or "2" in phase else 18,
        start_date="2021-01-15",
        completion_date="2023-03-01" if months_stale >= 18 else "2026-02-01",
        primary_completion_date="2022-12-01" if months_stale >= 18 else "2025-11-01",
        indication=indication,
        endpoints=["Safety", "Pharmacodynamic response", "Exploratory efficacy"],
        outcome_summary="Illustrative seed-data summary; verify against ClinicalTrials.gov before investment use.",
        adverse_events_summary="No severe safety conclusion is made in the MVP seed record. Needs verification.",
        url=f"https://clinicaltrials.gov/study/{nct_id}",
    )


def patent(asset_id: str, notes: str, confidence: float = 0.35) -> PatentExclusivity:
    return PatentExclusivity(
        asset_id=asset_id,
        patent_number="Needs verification",
        title="Placeholder IP/exclusivity record",
        owner="Needs verification",
        expiration_date="Needs verification",
        claim_type="composition/use/formulation unknown",
        orange_book_listed=False,
        orphan_exclusivity=False,
        data_exclusivity=False,
        pediatric_exclusivity=False,
        notes=notes,
        confidence=confidence,
    )


def seed_assets() -> list[Asset]:
    created = now_iso()
    items = [
        Asset(
            id="rare-dx-101",
            generic_name="FDX-101",
            brand_names=[],
            aliases=["rare complement modulator"],
            modality="small molecule",
            mechanism_of_action="Complement pathway modulation",
            target="Complement factor pathway",
            indication="Ultra-rare inflammatory vasculopathy",
            therapeutic_area="Rare disease / immunology",
            development_stage="Phase 2",
            regulatory_status="Investigational; orphan hypothesis only",
            foreign_approval_status="No known approval in seed record",
            current_owner="Small public biotech",
            original_inventor_or_institution="Academic medical center",
            license_status="Unknown; appears potentially licensable",
            asset_status="dormant",
            last_known_activity_date="2023-03-01",
            source_confidence=0.58,
            created_at=created,
            updated_at=created,
            tags=["rare", "human_data", "dormant", "orphan_potential"],
            assumptions=["Synthetic seed data for MVP demonstration; not an investment recommendation."],
        ),
        Asset(
            id="metab-204",
            generic_name="metabrenil",
            brand_names=[],
            aliases=["MB-204"],
            modality="small molecule",
            mechanism_of_action="Mitochondrial stress response activation",
            target="AMPK / mitochondrial pathway",
            indication="NASH fibrosis enrichment subgroup",
            therapeutic_area="Metabolic disease",
            development_stage="Phase 2 terminated",
            regulatory_status="Investigational",
            foreign_approval_status="None known",
            current_owner="Mid-cap company after portfolio reprioritization",
            original_inventor_or_institution="Private biotech",
            license_status="Unknown",
            asset_status="discontinued",
            last_known_activity_date="2022-04-15",
            source_confidence=0.45,
            created_at=created,
            updated_at=created,
            tags=["terminated", "subgroup_signal", "needs_review"],
            assumptions=["Subgroup signal is hypothetical and needs verification."],
        ),
        Asset(
            id="jp-cardio-77",
            generic_name="cardiovalate",
            brand_names=["Cardiovale"],
            aliases=["JP-CV77"],
            modality="small molecule",
            mechanism_of_action="Vascular smooth-muscle calcium sensitization modulator",
            target="Vascular tone pathway",
            indication="Pulmonary microvascular angina",
            therapeutic_area="Cardiovascular",
            development_stage="Foreign approved",
            regulatory_status="No obvious U.S. development in seed record",
            foreign_approval_status="Approved in Japan per synthetic seed record; needs verification",
            current_owner="Japanese specialty pharma",
            original_inventor_or_institution="Japanese pharma research group",
            license_status="Potential U.S. rights inquiry",
            asset_status="active",
            last_known_activity_date="2024-06-30",
            source_confidence=0.42,
            created_at=created,
            updated_at=created,
            tags=["foreign_approved", "505b2_hypothesis", "watchlist"],
            assumptions=["Foreign approval and label facts are placeholders pending PMDA/source verification."],
        ),
        Asset(
            id="derm-otc-12",
            generic_name="barrierstat",
            brand_names=["Barrierstat"],
            aliases=["DS-12"],
            modality="topical product",
            mechanism_of_action="Barrier repair and anti-inflammatory excipient blend",
            target="Skin barrier",
            indication="Atopic dermatitis adjunctive care",
            therapeutic_area="Dermatology",
            development_stage="Commercial",
            regulatory_status="Commercial product; regulatory class needs verification",
            foreign_approval_status="Unknown",
            current_owner="Specialty dermatology company",
            original_inventor_or_institution="Dermatology clinic network",
            license_status="Potential asset acquisition",
            asset_status="active",
            last_known_activity_date="2025-09-01",
            source_confidence=0.5,
            created_at=created,
            updated_at=created,
            tags=["commercial", "dermatology", "repositioning"],
            assumptions=["Commercial claims are synthetic placeholders."],
        ),
        Asset(
            id="gene-gt-9",
            generic_name="GTX-9",
            brand_names=[],
            aliases=["AAV9-neurogene"],
            modality="gene therapy",
            mechanism_of_action="AAV-mediated enzyme replacement",
            target="Lysosomal enzyme",
            indication="Pediatric neurodegenerative enzyme deficiency",
            therapeutic_area="Rare disease / gene therapy",
            development_stage="Phase 1/2",
            regulatory_status="Investigational; rare pediatric disease PRV hypothesis",
            foreign_approval_status="None known",
            current_owner="Venture-backed private company",
            original_inventor_or_institution="Children's hospital",
            license_status="Unknown",
            asset_status="active",
            last_known_activity_date="2025-12-01",
            source_confidence=0.52,
            created_at=created,
            updated_at=created,
            tags=["gene_therapy", "rare", "prv_potential", "cmc_risk"],
            assumptions=["CMC and PRV potential require specialist diligence."],
        ),
        Asset(
            id="academic-poc-33",
            generic_name="APOC-33",
            brand_names=[],
            aliases=["university kinase inhibitor"],
            modality="small molecule",
            mechanism_of_action="Selective inflammatory kinase inhibition",
            target="Inflammatory kinase",
            indication="Refractory uveitis",
            therapeutic_area="Ophthalmology / immunology",
            development_stage="Investigator Phase 1b",
            regulatory_status="Investigator-sponsored human proof-of-concept",
            foreign_approval_status="None known",
            current_owner="University technology transfer office",
            original_inventor_or_institution="University lab",
            license_status="Likely licensable through tech transfer",
            asset_status="dormant",
            last_known_activity_date="2023-08-15",
            source_confidence=0.49,
            created_at=created,
            updated_at=created,
            tags=["academic", "human_data", "dormant"],
            assumptions=["Tech-transfer status is illustrative and needs verification."],
        ),
        Asset(
            id="onc-pass-404",
            generic_name="pancheckib",
            brand_names=[],
            aliases=["PCK-404"],
            modality="small molecule",
            mechanism_of_action="Pan-checkpoint kinase inhibition",
            target="Multiple checkpoint kinases",
            indication="Unselected metastatic solid tumors",
            therapeutic_area="Oncology",
            development_stage="Failed Phase 2",
            regulatory_status="Investigational; no clear path",
            foreign_approval_status="None known",
            current_owner="Distressed oncology company",
            original_inventor_or_institution="Unknown",
            license_status="Unknown",
            asset_status="discontinued",
            last_known_activity_date="2021-02-01",
            source_confidence=0.4,
            created_at=created,
            updated_at=created,
            tags=["pass", "safety_signal", "crowded", "failed"],
            assumptions=["Bad/pass asset intentionally included for scoring calibration."],
        ),
        Asset(
            id="antiinfect-58",
            generic_name="mycoban",
            brand_names=[],
            aliases=["MCB-58"],
            modality="small molecule",
            mechanism_of_action="Mycobacterial cell-wall enzyme inhibitor",
            target="Cell-wall enzyme",
            indication="Nontuberculous mycobacterial infection",
            therapeutic_area="Anti-infective / rare disease",
            development_stage="Phase 2 dormant",
            regulatory_status="Investigational; orphan/LPAD hypothesis",
            foreign_approval_status="None known",
            current_owner="Large pharma discontinued asset list",
            original_inventor_or_institution="Large pharma",
            license_status="Potential non-core licensing",
            asset_status="dormant",
            last_known_activity_date="2022-11-30",
            source_confidence=0.46,
            created_at=created,
            updated_at=created,
            tags=["rare", "dormant", "large_pharma_noncore", "watchlist"],
            assumptions=["LPAD/orphan path is a hypothesis requiring regulatory counsel."],
        ),
        Asset(
            id="neuro-watch-17",
            generic_name="synaptoril",
            brand_names=[],
            aliases=["SYN-17"],
            modality="small molecule",
            mechanism_of_action="Synaptic vesicle modulation",
            target="SV2-family pathway",
            indication="Treatment-resistant focal seizure subgroup",
            therapeutic_area="Neurology",
            development_stage="Phase 2",
            regulatory_status="Investigational",
            foreign_approval_status="Unknown",
            current_owner="Small private neuroscience company",
            original_inventor_or_institution="Private biotech",
            license_status="Monitor",
            asset_status="unknown",
            last_known_activity_date="2024-02-10",
            source_confidence=0.44,
            created_at=created,
            updated_at=created,
            tags=["watchlist", "human_data", "needs_review"],
            assumptions=["Efficacy and safety facts need verification."],
        ),
        Asset(
            id="oph-505-22",
            generic_name="retinazide",
            brand_names=["Retinazide"],
            aliases=["RZ-22"],
            modality="reformulated small molecule",
            mechanism_of_action="Retinoid receptor modulation",
            target="Retinoid receptor",
            indication="Rare keratinizing ocular surface disease",
            therapeutic_area="Ophthalmology",
            development_stage="Repositioning candidate",
            regulatory_status="Possible 505(b)(2) hypothesis",
            foreign_approval_status="Legacy foreign use suggested by seed record; needs verification",
            current_owner="Legacy specialty pharma",
            original_inventor_or_institution="Legacy pharma",
            license_status="Potential option-to-license",
            asset_status="unknown",
            last_known_activity_date="2023-12-20",
            source_confidence=0.47,
            created_at=created,
            updated_at=created,
            tags=["505b2_hypothesis", "foreign_approved", "rare", "needs_review"],
            assumptions=["All repositioning and foreign-use claims are hypotheses until sourced."],
        ),
    ]

    for asset in items:
        asset.evidence = [
            ev(asset.id, 1, "clinical_trial", f"ClinicalTrials.gov seed record: {asset.generic_name}", f"Seed record indicates {asset.development_stage} activity in {asset.indication}.", f"https://clinicaltrials.gov/search?term={asset.generic_name}"),
            ev(asset.id, 2, "publication", f"PubMed query placeholder: {asset.generic_name}", "Publication support has not been verified in this offline MVP seed set. Needs verification.", f"https://pubmed.ncbi.nlm.nih.gov/?term={asset.generic_name}", 0.25),
            ev(asset.id, 3, "press_release", f"Portfolio status placeholder: {asset.current_owner}", f"Owner/status assessment is illustrative for MVP scoring and must be verified before outreach.", "https://example.com/synthetic-seed-source", 0.2),
        ]
        asset.trials = [trial(asset.id, f"NCT{abs(hash(asset.id)) % 90000000 + 10000000}", asset.development_stage, "Completed" if "failed" not in asset.tags else "Terminated", asset.current_owner, asset.indication, 24)]
        asset.patents = [patent(asset.id, "Public IP coverage not populated in MVP seed data. Needs verification.")]
    return items
